GET /repos/OWNER/REPO/commits?sha=feature%2Fbranch HTTP/1.1
Host: api.github.com
User-Agent: GitHub CLI 2.100.0
Accept: */*
Authorization: token sentinel
Content-Type: application/json; charset=utf-8
Time-Zone: UTC
X-Github-Api-Version: 2022-11-28
Accept-Encoding: gzip
Connection: close

