"""Local derived-image builds (ADR-0006/0015: no registry, no builder node).

Every container-host builds its own derived images when its desired state
declares them: a digest-pinned base + setup instructions + an optional
compiled knowledge tree copied from the node's applied config-distribution
tree (ADR-0048) — at BUILD time, never at container start (NODE-SUBSTRATE.md).
The deterministic tag and the instruction hash arrive computed from the
Control Node (one implementation, in control/configrepo.py); this module turns
a recipe into an image and stamps the metadata labels that heartbeats report,
so build skew across the fleet is visible from Control Node state instead of
being prevented.

The knowledge gate is fail-closed by identity (ADR-0048): the recipe's
``knowledge_pin`` is the per-tree content hash control computed at ingest, and
the build recomputes it over the applied tree before copying — a tag is a
complete statement of what a Run executed with, so an image is never built
from content that disagrees with the identity it would be tagged under. A
missing or off-pin tree defers the build (the node converges the distribution
first; the next pass retries).
"""

from __future__ import annotations

import shutil
import tempfile
import time
from pathlib import Path
from typing import Any

from theozolith_nodedaemon import configdist
from theozolith_nodedaemon.dockerctl import DockerCtl

LABEL_BASE_DIGEST = "theozolith.base-digest"
LABEL_INSTRUCTION_HASH = "theozolith.instruction-hash"
LABEL_BUILT_AT = "theozolith.built-at"

# The build-context directory the compiled knowledge tree is copied into and
# the in-image destination it lands at (the agent CLI's config root).
_CONTEXT_KNOWLEDGE = "knowledge"
_KNOWLEDGE_TARGET = "/home/ozolith/.claude/"


def dockerfile_for(image: dict[str, Any], built_at: str) -> str:
    """Render one derived-image recipe (wire form) as a Dockerfile."""
    lines = [
        "# Generated by theozolith-nodedaemon from the pinned build — do not edit.",
        f"FROM {image['base']}",
        # Base run images drop to an unprivileged user; setup instructions
        # (package installs) need root, so the build escalates and drops back.
        "USER root",
    ]
    lines.extend(f"RUN {instruction}" for instruction in image.get("setup", []))
    if image.get("knowledge", ""):
        # The compiled tree was staged into the build context by ensure_image
        # after verifying its content hash against the recipe's knowledge_pin
        # (ADR-0048). COPY of a directory copies its contents.
        lines.append(f"COPY --chown=ozolith:ozolith {_CONTEXT_KNOWLEDGE}/ {_KNOWLEDGE_TARGET}")
    lines += [
        # Keep the home usable under THEOZOLITH_CONTAINER_USER overrides,
        # exactly like the base image does.
        "RUN chmod -R a+rwX /home/ozolith",
        f'LABEL {LABEL_BASE_DIGEST}="{image["base_digest"]}"',
        f'LABEL {LABEL_INSTRUCTION_HASH}="{image["instruction_hash"]}"',
        f'LABEL {LABEL_BUILT_AT}="{built_at}"',
        "USER ozolith",
        "",
    ]
    return "\n".join(lines)


def stage_knowledge(image: dict[str, Any], dist_root: Path | None, context: Path) -> str | None:
    """Copy the recipe's knowledge tree from the applied config-distribution
    root into the build context and verify THE COPY against the recipe's pin
    — hash exactly the bytes the build will consume, so a tree swapped between
    check and copy can never bake. Returns a defer reason, or ``None`` when
    the context is staged (or the recipe references no knowledge). A reason
    means DEFER: the distribution has not converged to the tree this recipe
    was pinned against (ADR-0042 advisory skew doing its job), or the applied
    tree is malformed (repaired by the convergence loop)."""
    ref = image.get("knowledge", "")
    if not ref:
        return None
    prefix = configdist.KNOWLEDGE_DIR + "/"
    name = ref[len(prefix) :]
    if not ref.startswith(prefix) or not name or "/" in name:
        return f"recipe knowledge reference {ref!r} is not knowledge/<name>"
    if dist_root is None:
        return "no verified config-distribution tree is applied yet"
    staged = context / _CONTEXT_KNOWLEDGE
    try:
        shutil.copytree(dist_root / configdist.KNOWLEDGE_DIR / name, staged, symlinks=False)
    except FileNotFoundError:
        return f"applied config-distribution tree has no knowledge/{name}"
    except OSError as exc:
        return f"cannot stage knowledge/{name}: {exc}"
    pin = image.get("knowledge_pin", "")
    try:
        copied = configdist.tree_hash(staged)
    except configdist.ConfigDistError as exc:
        return f"staged knowledge/{name} failed verification: {exc}"
    if not copied or copied != pin:
        return (
            f"applied knowledge/{name} hashes {copied[:12] or '(empty)'}, recipe"
            f" pins {pin[:12] or '(none)'} — distribution and desired state"
            " disagree; converging first"
        )
    return None


def ensure_image(
    docker: DockerCtl,
    image: dict[str, Any],
    *,
    force: bool = False,
    log,
    dist_root: Path | None = None,
) -> bool:
    """Build the recipe unless its deterministic tag already exists.

    Returns True when a build ran. ``force`` is the rebuild command: same
    tag, fresh layers (--no-cache), new built-at label. ``dist_root`` is the
    node's VERIFIED applied config-distribution tree; a recipe referencing
    knowledge is built only when that tree carries the referenced tree at
    exactly the recipe's pin (ADR-0048) — otherwise the build defers to a
    later pass.
    """
    tag = image["tag"]
    if not force and docker.image_exists(tag):
        return False
    built_at = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    with tempfile.TemporaryDirectory(prefix="theozolith-build-") as context:
        reason = stage_knowledge(image, dist_root, Path(context))
        if reason:
            log(f"deferring derived image {tag}: {reason}")
            return False
        (Path(context) / "Dockerfile").write_text(dockerfile_for(image, built_at), encoding="utf-8")
        log(f"building derived image {tag} (base {image['base_digest'][:19]}…)")
        docker.build(Path(context), tag, no_cache=force)
    return True


def image_status(docker: DockerCtl, image: dict[str, Any]) -> dict[str, str]:
    """What heartbeats report for one declared image on this host."""
    labels = docker.image_labels(image["tag"]) if docker.image_exists(image["tag"]) else {}
    return {
        "name": image["name"],
        "tag": image["tag"] if labels else "",
        "base_digest": labels.get(LABEL_BASE_DIGEST, ""),
        "instruction_hash": labels.get(LABEL_INSTRUCTION_HASH, ""),
        "built_at": labels.get(LABEL_BUILT_AT, ""),
    }
