"""Local derived-image builds (ADR-0006/0015: no registry, no builder node).

Every container-host builds its own derived images when its desired state
declares them: a digest-pinned base + setup instructions + an optional
Knowledge Source baked by the M1 bake CLI — at BUILD time, never at
container start (NODE-SUBSTRATE.md). The deterministic tag and the
instruction hash arrive computed from the Control Node (one implementation,
in control/configrepo.py); this module turns a recipe into an image and
stamps the metadata labels that heartbeats report, so build skew across the
fleet is visible from Control Node state instead of being prevented.
"""

from __future__ import annotations

import shlex
import tempfile
import time
from pathlib import Path
from typing import Any

from theozolith_nodedaemon.dockerctl import DockerCtl

LABEL_BASE_DIGEST = "theozolith.base-digest"
LABEL_INSTRUCTION_HASH = "theozolith.instruction-hash"
LABEL_BUILT_AT = "theozolith.built-at"


def dockerfile_for(image: dict[str, Any], built_at: str) -> str:
    """Render one derived-image recipe (wire form) as a Dockerfile."""
    lines = [
        "# Generated by theozolith-nodedaemon from the Config Repo — do not edit.",
        f"FROM {image['base']}",
        # Base run images drop to an unprivileged user; setup instructions
        # (package installs) need root, so the build escalates and drops back.
        "USER root",
    ]
    lines.extend(f"RUN {instruction}" for instruction in image.get("setup", []))
    source = image.get("knowledge_source", "")
    if source:
        pin = image.get("knowledge_pin", "")
        lines.append(
            "RUN theozolith-knowledge bake"
            f" --source {shlex.quote(source)}"
            + (f" --pin {shlex.quote(pin)}" if pin else "")
            + " --target /home/ozolith/.claude"
            " && chown -R ozolith:ozolith /home/ozolith/.claude"
        )
    lines += [
        # Keep the home usable under THEOZOLITH_CONTAINER_USER overrides,
        # exactly like the base image does.
        "RUN chmod -R a+rwX /home/ozolith",
        f'LABEL {LABEL_BASE_DIGEST}="{image["base_digest"]}"',
        f'LABEL {LABEL_INSTRUCTION_HASH}="{image["instruction_hash"]}"',
        f'LABEL {LABEL_BUILT_AT}="{built_at}"',
        "USER ozolith",
        "",
    ]
    return "\n".join(lines)


def ensure_image(docker: DockerCtl, image: dict[str, Any], *, force: bool = False, log) -> bool:
    """Build the recipe unless its deterministic tag already exists.

    Returns True when a build ran. ``force`` is the rebuild command: same
    tag, fresh layers (--no-cache), new built-at label.
    """
    tag = image["tag"]
    if not force and docker.image_exists(tag):
        return False
    built_at = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    with tempfile.TemporaryDirectory(prefix="theozolith-build-") as context:
        (Path(context) / "Dockerfile").write_text(dockerfile_for(image, built_at), encoding="utf-8")
        log(f"building derived image {tag} (base {image['base_digest'][:19]}…)")
        docker.build(Path(context), tag, no_cache=force)
    return True


def image_status(docker: DockerCtl, image: dict[str, Any]) -> dict[str, str]:
    """What heartbeats report for one declared image on this host."""
    labels = docker.image_labels(image["tag"]) if docker.image_exists(image["tag"]) else {}
    return {
        "name": image["name"],
        "tag": image["tag"] if labels else "",
        "base_digest": labels.get(LABEL_BASE_DIGEST, ""),
        "instruction_hash": labels.get(LABEL_INSTRUCTION_HASH, ""),
        "built_at": labels.get(LABEL_BUILT_AT, ""),
    }
