"""Claude compiler: map a knowledge root onto the Claude config layout.

Mapping rules (ADR-0009):

    AGENTS.md              -> <target>/CLAUDE.md          (marker + verbatim body)
    skills/<name>/         -> <claude-dir>/skills/<name>/
    agents/claude/<n>.md   -> <claude-dir>/agents/<n>.md
    workflows/<name>       -> <claude-dir>/workflows/<name>

where <claude-dir> is the target root itself in global scope (e.g. ~/.claude)
and <target>/.claude in project scope. CLAUDE.md is always a generated copy of
AGENTS.md, never a source (AGENTIC-CODING-PIPELINE.md, agent swap boundary).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from theozolith_knowledge.model import IGNORED_NAMES, KnowledgeError, KnowledgeRoot

GENERATED_MARKER = (
    "<!-- Generated by TheOzolith knowledge machinery from AGENTS.md. "
    "Do not edit: change AGENTS.md and re-run the sync (ADR-0001). -->"
)

SCOPES = ("global", "project")


@dataclass(frozen=True)
class FileEntry:
    content: bytes
    executable: bool = False


# Target-root-relative POSIX path -> file to place there.
FileSet = dict[str, FileEntry]


def _entry(path: Path) -> FileEntry:
    return FileEntry(
        content=path.read_bytes(),
        executable=bool(path.stat().st_mode & 0o100),
    )


def _walk_files(base: Path) -> list[tuple[str, FileEntry]]:
    out = []
    for path in sorted(base.rglob("*")):
        rel = path.relative_to(base)
        if any(part in IGNORED_NAMES for part in rel.parts):
            continue
        if path.is_file():
            out.append((rel.as_posix(), _entry(path)))
    return out


def compile_claude(root: KnowledgeRoot, scope: str) -> FileSet:
    """Compile a knowledge root into the files Claude expects, keyed by
    target-root-relative path."""
    if scope not in SCOPES:
        raise KnowledgeError(f"unknown scope {scope!r}; expected one of {SCOPES}")
    prefix = "" if scope == "global" else ".claude/"

    files: FileSet = {}
    if root.agents_md is not None:
        body = root.agents_md.read_bytes()
        files["CLAUDE.md"] = FileEntry(GENERATED_MARKER.encode() + b"\n\n" + body)
    for skill in root.skills:
        for rel, entry in _walk_files(skill.path):
            files[f"{prefix}skills/{skill.name}/{rel}"] = entry
    for agent in root.claude_agents:
        files[f"{prefix}agents/{agent.name}.md"] = _entry(agent.path)
    for workflow in root.workflows:
        if workflow.path.is_dir():
            for rel, entry in _walk_files(workflow.path):
                files[f"{prefix}workflows/{workflow.name}/{rel}"] = entry
        else:
            files[f"{prefix}workflows/{workflow.name}"] = _entry(workflow.path)
    return files
