"""Control Node configuration: the ``~/.theozolith/`` partition + control.toml.

Storage is partitioned by durability class (ADR-0024): ``configs/`` is the
Config Repo working home (a git repo — control.toml, stacks/, images/,
product.toml), ``secrets/`` is its sibling and never inside any git tree
(master.key, CA keypair, TLS material, admin password hash, admin token,
store.db), ``cache/`` is deletable at any time (cache.db, served build
artifacts), and ``logs/`` holds the terminal audit log.

Tier-2 tunables load from ``control.toml`` (ADR-0023) with every setting
shipping a default — the ADR-0004 deletion test boots with no Config Repo
at all — and ``THEOZOLITH_*`` environment variables are validated expert
overrides, no longer the configuration surface (`.env` is deleted).

Credentials: the admin bearer token (machine credential, ADR-0015 —
generated by init into ``secrets/admin-token``) and the admin password hash
(browser credential, ``secrets/admin-password``). The shared node token is
gone (ADR-0023): nodes authenticate with per-node tokens minted at
provisioning, verified against ``store.db``.
"""

from __future__ import annotations

import os
from collections.abc import Mapping
from dataclasses import dataclass, fields
from pathlib import Path
from typing import Any

from theozolith_worker.config import ConfigError, env_value

from theozolith_control import controltoml

DEFAULT_DATA_DIR = "~/.theozolith"
# Root-mediated bare-metal setup (ADR-0034): `sudo theozolith init` and the
# systemd unit's service user share one fixed system path (mirroring the
# nodes' /var/lib/theozolith), so `sudo theozolith build` finds the admin
# token with no environment. THEOZOLITH_DATA_DIR still overrides.
DEFAULT_ROOT_DATA_DIR = "/var/lib/theozolith-control"

ADMIN_TOKEN_FILE = "admin-token"
ADMIN_PASSWORD_FILE = "admin-password"
MASTER_KEY_FILE = "master.key"
STORE_DB_FILE = "store.db"
CACHE_DB_FILE = "cache.db"


@dataclass(frozen=True)
class ControlSettings:
    data_dir: Path  # ~/.theozolith — the partitioned home (ADR-0024)
    config_repo: Path  # the Config Repo working home (ADR-0006), configs/
    admin_token: str  # the machine credential: CLI + API ("" until init)
    repo: str | None  # target repo (owner/name) for dispatch + janitor
    github_token: str | None  # the control PAT (claim writes, janitor)
    api_url: str = "https://api.github.com"
    # Tier-2 tunables (control.toml [settings]; ADR-0023). Defaults here
    # mirror controltoml.SETTINGS — load_settings always passes them in.
    heartbeat_seconds: float = 60.0
    zombie_grace_seconds: float = 600.0
    janitor_sweep_seconds: float = 60.0
    # ADR-0017: a grant with no claimed event inside this window is released.
    activation_window_seconds: float = 60.0
    # ADR-0016 cache-not-archive: progress-telemetry byte budget (oldest-first
    # eviction; terminal events are never evicted).
    tail_budget_bytes: int = 10 * 1024**3
    # ADR-0015 revision: consecutive off-pin heartbeats before the restart
    # escalation (a theozolith.error follows after as many again).
    offpin_beats: int = 3
    # Concurrent web-terminal sessions; excess connects are refused before
    # any attach process launches (ADR-0019).
    terminal_session_cap: int = 8
    # Absolute browser-session expiry (ADR-0023: stateful revocable sessions).
    session_days: float = 30.0
    stop_grace_seconds: float = 30.0
    # The dedicated plaintext bootstrap listener (ADR-0023): CA cert, public
    # origin, canonical control URL — never mounted on the HTTPS app.
    bootstrap_port: int = controltoml.DEFAULT_BOOTSTRAP_PORT
    installer_url: str = controltoml.DEFAULT_INSTALLER_URL
    # True only when the server terminates TLS itself or an operator
    # explicitly opted into insecure dev mode: gates the secret endpoints.
    secrets_channel_ok: bool = False
    # The LAN address nodes AND browsers dial (ADR-0031/0034; the slug
    # origin is retired) — this operator-confirmed, init-persisted address
    # feeds every join-string mint, the bootstrap listener's /control-url,
    # the certificate SAN, and the exact browser Host/Origin. Never
    # detected at mint time.
    control_ip: str = ""
    # The EXTERNAL https port browsers and nodes dial (ADR-0034) — a
    # read-only [control] field beside the IP; independent of the Uvicorn
    # bind port (docker maps external onto the bind; the bare-metal systemd
    # unit binds it directly).
    control_port: int = 443
    # True when serve terminates TLS: decides the session cookie's name and
    # Secure flag (__Host- + Secure over TLS; a plain dev cookie otherwise).
    serve_tls: bool = False

    # -- the partition (ADR-0024) ------------------------------------------

    @property
    def secrets_dir(self) -> Path:
        return self.data_dir / "secrets"

    @property
    def cache_dir(self) -> Path:
        return self.data_dir / "cache"

    @property
    def logs_dir(self) -> Path:
        return self.data_dir / "logs"

    @property
    def store_db_path(self) -> Path:
        """store.db: encrypted secret ciphertext + per-node tokens."""
        return self.secrets_dir / STORE_DB_FILE

    @property
    def cache_db_path(self) -> Path:
        """cache.db: deletable by construction (state, events, sessions,
        join tokens, unregistered-node sightings)."""
        return self.cache_dir / CACHE_DB_FILE

    @property
    def key_path(self) -> Path:
        return self.secrets_dir / MASTER_KEY_FILE

    @property
    def tls_dir(self) -> Path:
        return self.secrets_dir / "tls"

    @property
    def admin_token_path(self) -> Path:
        return self.secrets_dir / ADMIN_TOKEN_FILE

    @property
    def admin_password_path(self) -> Path:
        return self.secrets_dir / ADMIN_PASSWORD_FILE

    @property
    def terminal_audit_path(self) -> Path:
        return self.logs_dir / "terminal-audit.log"

    @property
    def artifacts_dir(self) -> Path:
        """Built distributions the developer path serves for node pulls
        (ADR-0015 amendment 2026-07-22): one directory per pinned version.
        Under cache/ — losing it costs one `theozolith build` re-run."""
        return self.cache_dir / "artifacts"

    @property
    def coordination_jobs_enabled(self) -> bool:
        """Dispatch + janitor need a GitHub identity and a target repo."""
        return bool(self.repo and self.github_token)


_SETTING_FIELDS = {f.name for f in fields(ControlSettings)}


def _read_secret_file(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8").strip()
    except OSError:
        return ""


def load_settings(environ: Mapping[str, str] | None = None) -> ControlSettings:
    environ = os.environ if environ is None else environ

    repo = env_value(environ, "THEOZOLITH_REPO")
    if repo and "/" not in repo:
        raise ConfigError(f"THEOZOLITH_REPO must be owner/name, got {repo!r}")

    default_dir = DEFAULT_ROOT_DATA_DIR if os.geteuid() == 0 else DEFAULT_DATA_DIR
    data_dir = Path(
        env_value(environ, "THEOZOLITH_DATA_DIR", default_dir) or default_dir
    ).expanduser()
    config_repo = Path(
        env_value(environ, "THEOZOLITH_CONFIG_REPO") or (data_dir / "configs")
    ).expanduser()

    # Tier-2: shipped defaults <- control.toml <- validated env overrides.
    # The persisted control_port rides the same fail-closed path: a
    # malformed value is a configuration error, never a silent 443.
    try:
        tunables: dict[str, Any] = controltoml.read_values(config_repo)
        for setting in controltoml.SETTINGS:
            raw = env_value(environ, setting.env)
            if raw:
                tunables[setting.key] = setting.coerce(raw, source=setting.env)
        control_port = controltoml.read_control_port(config_repo)
    except controltoml.ControlTomlError as exc:
        raise ConfigError(str(exc)) from exc

    return ControlSettings(
        data_dir=data_dir,
        config_repo=config_repo,
        # The machine credential: init writes it to secrets/admin-token; the
        # env var stays as the container/dev override.
        admin_token=env_value(environ, "THEOZOLITH_ADMIN_TOKEN")
        or _read_secret_file(data_dir / "secrets" / ADMIN_TOKEN_FILE),
        repo=repo,
        github_token=env_value(environ, "CONTROL_GITHUB_TOKEN")
        or env_value(environ, "GITHUB_TOKEN"),
        api_url=env_value(environ, "THEOZOLITH_API_URL", "https://api.github.com") or "",
        control_ip=controltoml.read_control_ip(config_repo),
        control_port=control_port,
        **{key: value for key, value in tunables.items() if key in _SETTING_FIELDS},
    )
