from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import pytest
from theozolith_knowledge.bake import RECEIPT_NAME, bake
from theozolith_knowledge.sync import MANIFEST_NAME
from treeutil import GOLDEN, PACKAGE_ROOT, tree_snapshot

IGNORE_BOOKKEEPING = frozenset({MANIFEST_NAME, RECEIPT_NAME})


def _run(args: list[str], cwd: Path) -> str:
    proc = subprocess.run(args, cwd=cwd, capture_output=True, text=True)
    assert proc.returncode == 0, f"{args} failed:\n{proc.stdout}\n{proc.stderr}"
    return proc.stdout.strip()


def _git(args: list[str], cwd: Path) -> str:
    return _run(["git", "-c", "user.email=test@example.com", "-c", "user.name=test", *args], cwd)


def make_pinned_repo(sample_knowledge: Path, where: Path) -> tuple[Path, str, str]:
    """Fixture knowledge as a git repo with two commits; returns
    (repo, first_sha, second_sha) — the second commit changes AGENTS.md."""
    repo = where / "knowledge-repo"
    shutil.copytree(sample_knowledge, repo)
    _git(["init", "--quiet", "-b", "main"], repo)
    _git(["add", "-A"], repo)
    _git(["commit", "--quiet", "-m", "one"], repo)
    first = _git(["rev-parse", "HEAD"], repo)
    (repo / "AGENTS.md").write_text("# Changed after the pin\n")
    _git(["add", "-A"], repo)
    _git(["commit", "--quiet", "-m", "two"], repo)
    second = _git(["rev-parse", "HEAD"], repo)
    return repo, first, second


def test_bake_installs_the_pinned_commit(tmp_path, sample_knowledge):
    repo, first, second = make_pinned_repo(sample_knowledge, tmp_path)
    target = tmp_path / "claude"

    result = bake(str(repo), first, target)

    assert result.commit == first != second
    # The pin wins over the repo's later HEAD: the tree matches the golden
    # tree built from the unchanged fixture.
    assert tree_snapshot(target, IGNORE_BOOKKEEPING) == tree_snapshot(GOLDEN / "claude_global")
    receipt = json.loads((target / RECEIPT_NAME).read_text())
    assert receipt["commit"] == first
    assert receipt["pin"] == first


def test_bake_branch_pin_resolves_to_head(tmp_path, sample_knowledge):
    repo, _first, second = make_pinned_repo(sample_knowledge, tmp_path)
    target = tmp_path / "claude"

    result = bake(str(repo), "main", target)

    assert result.commit == second
    assert b"Changed after the pin" in (target / "CLAUDE.md").read_bytes()


def test_bake_is_idempotent(tmp_path, sample_knowledge):
    repo, first, _second = make_pinned_repo(sample_knowledge, tmp_path)
    target = tmp_path / "claude"
    bake(str(repo), first, target)

    result = bake(str(repo), first, target)

    assert not result.report.changed


# --- Acceptance 3: a sample Dockerfile invoking the bake CLI produces an
# image containing the compiled knowledge; nothing runs at container start.

# Mirrors knowledge/examples/bake/Dockerfile, with the Knowledge Source
# COPY'd into the image so the build needs no external git host.
DOCKERFILE = """\
FROM python:3.13-slim
RUN apt-get update && apt-get install -y --no-install-recommends git \\
    && rm -rf /var/lib/apt/lists/*
COPY knowledge /opt/theozolith-knowledge
RUN pip install --no-cache-dir /opt/theozolith-knowledge
COPY knowledge-repo /srv/knowledge-repo
ARG KNOWLEDGE_PIN
RUN theozolith-knowledge bake --source /srv/knowledge-repo \\
    --pin "$KNOWLEDGE_PIN" --target /root/.claude
"""


def _docker_available() -> bool:
    docker = shutil.which("docker")
    if docker is None:
        return False
    return subprocess.run(["docker", "info"], capture_output=True).returncode == 0


@pytest.mark.skipif(not _docker_available(), reason="docker unavailable")
def test_bake_in_docker_build(tmp_path, sample_knowledge):
    context = tmp_path / "context"
    context.mkdir()
    shutil.copytree(
        PACKAGE_ROOT,
        context / "knowledge",
        ignore=shutil.ignore_patterns("tests", "examples", "__pycache__", "*.egg-info"),
    )
    _repo, first, _second = make_pinned_repo(sample_knowledge, context)
    (context / "Dockerfile").write_text(DOCKERFILE)
    tag = f"theozolith-bake-test:{first[:12]}"

    _run(
        ["docker", "build", "--quiet", "-t", tag, "--build-arg", f"KNOWLEDGE_PIN={first}", "."],
        context,
    )
    try:
        claude_md = _run(["docker", "run", "--rm", tag, "cat", "/root/.claude/CLAUDE.md"], context)
        assert "Sample Knowledge" in claude_md
        assert "Generated by TheOzolith knowledge machinery" in claude_md

        # The baked skill script is present and executable.
        hello = _run(
            ["docker", "run", "--rm", tag, "/root/.claude/skills/greet/scripts/hello.sh"],
            context,
        )
        assert hello == "hello, world"

        receipt = json.loads(
            _run(["docker", "run", "--rm", tag, "cat", f"/root/.claude/{RECEIPT_NAME}"], context)
        )
        assert receipt["commit"] == first

        # Nothing executes at container start: entrypoint/cmd come from the
        # base image, with no sync or setup hook of ours.
        config = _run(
            ["docker", "inspect", "-f", "{{json .Config.Entrypoint}} {{json .Config.Cmd}}", tag],
            context,
        )
        assert "theozolith" not in config
        assert "bake" not in config
    finally:
        subprocess.run(["docker", "rmi", "-f", tag], capture_output=True)
